//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsuReservation.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("IsuReservation.Resources.MessageResource", typeof(MessageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string NameFieldEmpty {
            get {
                return ResourceManager.GetString("NameFieldEmpty", resourceCulture);
            }
        }
        
        internal static string BirthDayFieldEmpty {
            get {
                return ResourceManager.GetString("BirthDayFieldEmpty", resourceCulture);
            }
        }
        
        internal static string ContactTypeFieldEmpty {
            get {
                return ResourceManager.GetString("ContactTypeFieldEmpty", resourceCulture);
            }
        }
        
        internal static string AgeOlderThan18 {
            get {
                return ResourceManager.GetString("AgeOlderThan18", resourceCulture);
            }
        }
        
        internal static string InvalidDate {
            get {
                return ResourceManager.GetString("InvalidDate", resourceCulture);
            }
        }
        
        internal static string ContactNotFound {
            get {
                return ResourceManager.GetString("ContactNotFound", resourceCulture);
            }
        }
        
        internal static string ContactAlreadyExist {
            get {
                return ResourceManager.GetString("ContactAlreadyExist", resourceCulture);
            }
        }
        
        internal static string DateFieldEmpty {
            get {
                return ResourceManager.GetString("DateFieldEmpty", resourceCulture);
            }
        }
        
        internal static string TimeFieldEmpty {
            get {
                return ResourceManager.GetString("TimeFieldEmpty", resourceCulture);
            }
        }
        
        internal static string InvalidTime {
            get {
                return ResourceManager.GetString("InvalidTime", resourceCulture);
            }
        }
        
        internal static string DestinationFieldEmpty {
            get {
                return ResourceManager.GetString("DestinationFieldEmpty", resourceCulture);
            }
        }
        
        internal static string ReservationAlreadyExist {
            get {
                return ResourceManager.GetString("ReservationAlreadyExist", resourceCulture);
            }
        }
        
        internal static string UnhandledError {
            get {
                return ResourceManager.GetString("UnhandledError", resourceCulture);
            }
        }
        
        internal static string ReservationNotFound {
            get {
                return ResourceManager.GetString("ReservationNotFound", resourceCulture);
            }
        }
        
        internal static string ContactFieldEmpty {
            get {
                return ResourceManager.GetString("ContactFieldEmpty", resourceCulture);
            }
        }
        
        internal static string DestinationNotFound {
            get {
                return ResourceManager.GetString("DestinationNotFound", resourceCulture);
            }
        }
        
        internal static string InvalidRankingValue {
            get {
                return ResourceManager.GetString("InvalidRankingValue", resourceCulture);
            }
        }
    }
}
